version: '3.8'

services:
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api/v1
    depends_on:
      - backend
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next

  backend:
    build:
      context: ./src/subnet
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=duckdb:///app/datasets.db
    volumes:
      - ./src/subnet:/app
      - /app/venv
      - /app/__pycache__
      - ./src/subnet/datasets.db:/app/datasets.db

volumes:
  datasets_data:
